
export const userData = [
    {
        name: 'Jan',
        "Active Users": 332,
    },
    {
        name: 'Feb',
        "Active Users": 445,
    },
    {
        name: 'Mar',
        "Active Users": 676,
    },
    {
        name: 'Apr',
        "Active Users": 788,
    },
    {
        name: 'May',
        "Active Users": 232,
    },
    {
        name: 'Jun',
        "Active Users": 775,
    },
    {
        name: 'July',
        "Active Users": 889,
    },
    {
        name: 'Aug',
        "Active Users": 312,
    },
    {
        name: 'Sep',
        "Active Users": 655,
    },
    {
        name: 'Oct',
        "Active Users": 987,
    },
    {
        name: 'Nov',
        "Active Users": 123,
    },
    {
        name: 'Dec',
        "Active Users": 656,
    },
  ];


  export const userRows = [
    {   id: 1, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 2, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 3, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 4, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 5, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 6, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 7, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 8, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 9, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 10, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
    {   id: 11, 
        username: 'Suraj K S', 
        avatar : "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Elon_Musk_Royal_Society_%28crop1%29.jpg/220px-Elon_Musk_Royal_Society_%28crop1%29.jpg",
        email : "surajks28101999@gmail.com",
        status : "Active",
        transaction : "$120.00",
    },
  ];